### ISSUE TITLE
viz_dist directory does not exist when running ReDel from source

### ISSUE THREAD

**Issue by garkpit** [zhudotexe/redel#2]
Hi :)
redel looks amazing! I can't wait to play with it..

**Describe the bug**
I have cloned the main branch
and set up a conda environment
and done playwright install chromium
and done python -m pip install -r requirements.txt

however, when I run the server.py I get this error

(redel_env) (base) Jay@Yummy redel % python -m server.py                                                                    
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/Jay/Dev/AI/redel/server.py", line 50, in <module>
    server = VizServer(ai)
             ^^^^^^^^^^^^^
  File "/Users/Jay/Dev/AI/redel/redel/server/server.py", line 62, in __init__
    self.setup_app()
  File "/Users/Jay/Dev/AI/redel/redel/server/server.py", line 203, in setup_app
    self.fastapi.mount("/", StaticFiles(directory=VIZ_DIST, html=True), name="viz")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/redel_env/lib/python3.11/site-packages/starlette/staticfiles.py", line 59, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory '/Users/Jay/Dev/AI/redel/redel/server/viz_dist' does not exist

**Environment (please complete the following information):**
 - OS: macOS 
 - GPU: Apple silicon
 
Kindly advise a solution. 

ps. the server.py example at readthedocs has a couple of bugs in it. After fixing those I get the same issue.

**Comment by zhudotexe** [comment]
Ah, if you've cloned ReDel from Git rather than installing from pip, you'll need to build the frontend yourself. You can do this (if you have Node 18+ installed; if not check out `nvm`) by using:
```bash
cd viz
npm run build
cd ..
```

This should create the `redel/server/viz_dist` directory the frontend serves from. I'll add an extra check for this in the server code.

**Comment by garkpit** [comment]
That's great - thank you :)
